In [1]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [2]:
# Answer Here

array_3d = np.arange(24).reshape(2,3,4)
print("The sum of all the elements in the array is :: \n", array_3d.sum())


The sum of all the elements in the array is :: 
 276


# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [3]:
# Answer Here
array_4d = np.random.randint(0,10,size=(2,3,4,5))
array_4d

array([[[[8, 6, 9, 9, 2],
         [6, 8, 6, 8, 9],
         [7, 6, 1, 4, 8],
         [0, 2, 1, 1, 6]],

        [[8, 1, 8, 5, 2],
         [8, 0, 7, 4, 4],
         [7, 9, 1, 2, 2],
         [6, 0, 5, 9, 4]],

        [[8, 0, 3, 3, 2],
         [2, 9, 5, 2, 4],
         [8, 4, 0, 6, 9],
         [7, 6, 0, 5, 4]]],


       [[[0, 9, 5, 2, 9],
         [0, 2, 0, 4, 9],
         [1, 8, 1, 8, 6],
         [8, 0, 7, 6, 6]],

        [[6, 0, 0, 0, 6],
         [8, 1, 1, 9, 0],
         [8, 5, 0, 3, 5],
         [8, 3, 1, 4, 2]],

        [[1, 6, 9, 8, 2],
         [5, 3, 5, 4, 3],
         [3, 3, 8, 5, 3],
         [0, 4, 7, 5, 0]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [4]:
# Answer Here
("The mean along second axis (axis 1) is :: ",array_4d.mean(axis=1))

('The mean along second axis (axis 1) is :: ',
 array([[[8.        , 2.33333333, 6.66666667, 5.66666667, 2.        ],
         [5.33333333, 5.66666667, 6.        , 4.66666667, 5.66666667],
         [7.33333333, 6.33333333, 0.66666667, 4.        , 6.33333333],
         [4.33333333, 2.66666667, 2.        , 5.        , 4.66666667]],
 
        [[2.33333333, 5.        , 4.66666667, 3.33333333, 5.66666667],
         [4.33333333, 2.        , 2.        , 5.66666667, 4.        ],
         [4.        , 5.33333333, 3.        , 5.33333333, 4.66666667],
         [5.33333333, 2.33333333, 5.        , 5.        , 2.66666667]]]))

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [5]:

temperature_array = np.random.randint(-15,50,size=(7,24,60))
avg_temp = np.mean(temperature_array, axis=(1, 2))
print(avg_temp)

[17.35486111 16.31319444 17.46944444 17.17708333 17.84513889 17.12152778
 16.86597222]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [6]:
# Answer Here

np.random.seed(0)
sensor_data = np.random.randint(-15,50,size=(4,7,24,60))
max_sensor = np.mean(sensor_data,axis=(1,2,3))
print(max_sensor)



[16.90902778 17.32470238 17.18888889 16.84761905]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [7]:

data_printer = np.arange(15000).reshape(100, 50, 3)

average_length = np.mean(data_printer[:, :, 0])  
average_width = np.mean(data_printer[:, :, 1])   
average_height = np.mean(data_printer[:, :, 2])  

print("Average length across all objects:", average_length)
print("Average width across all objects:", average_width)
print("Average height across all objects:", average_height)


Average length across all objects: 7498.5
Average width across all objects: 7499.5
Average height across all objects: 7500.5


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [8]:
import numpy as np


data = np.arange(210).reshape(5,6,7)

#total measurement
total_msr = data.size
print("Total number of measurements are :: ",total_msr)

#average measurement
avg_msr = np.mean(data)
print("average measurement value is :: ",avg_msr)

#std
std_meas = np.std(data)
print("The standard deviation of measurement is :: ",std_meas)

#minimum value
min_meas = np.min(data)
print("The minimum  measurement value is :: ",min_meas)

#maximum value
max_meas = np.max(data)
print("The minimum  measurement value is :: ",max_meas)



Total number of measurements are ::  210
average measurement value is ::  104.5
The standard deviation of measurement is ::  60.621090939265244
The minimum  measurement value is ::  0
The minimum  measurement value is ::  209
