# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

In [3]:
import numpy as np

### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [4]:
# Answer here
array_2d = np.arange(28).reshape(2,14)
array_2d[0] = np.arange(10,80,5)
array_2d[1] = np.arange(5,47,3)
print("The specified 2d array with step of 5 in row 1 and step of 3 in row 2  is :: \n",array_2d)


The specified 2d array with step of 5 in row 1 and step of 3 in row 2  is :: 
 [[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [5]:
# Answer here
print("The 5,7 and 11 column is :: \n", array_2d[:,[5,7,11]])

The 5,7 and 11 column is :: 
 [[35 45 65]
 [20 26 38]]


### Select the 2nd row and fourth-last to second-last columns

In [6]:
#Answer here

print("The second row and fourth-last to second-last column is :: \n", array_2d[1,-4:-1])

The second row and fourth-last to second-last column is :: 
 [35 38 41]


### Select 3rd to 3rd last columns skipping every second column

In [7]:
# Answer here

print("The 3rd to 3rd-last skipping column every second column is :: \n", array_2d[:,3:-2:2])

The 3rd to 3rd-last skipping column every second column is :: 
 [[25 35 45 55 65]
 [14 20 26 32 38]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [8]:
# Answer here
print("The 3rd to 3rd-last skipping every second column in reverse is :: \n", array_2d[:,-3:2:-2])

The 3rd to 3rd-last skipping every second column in reverse is :: 
 [[65 55 45 35 25]
 [38 32 26 20 14]]


### We will work with the following array:

In [9]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [10]:
# Answer here
print("The 3rd and last row with 2nd and last column is :: \n",a[2::2,1::3])

The 3rd and last row with 2nd and last column is :: 
 [[11 14]
 [21 24]]


### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [11]:
# Answer here


print("The extracted sub-arrays are :: \n ", a[::2,2:4])

The extracted sub-arrays are :: 
  [[ 2  3]
 [12 13]
 [22 23]]


### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [12]:
# Answer here
print("The extraced sub-arrays using fancy/location indexing are :: \n", a[[1,3,4],1:4:2])

The extraced sub-arrays using fancy/location indexing are :: 
 [[ 6  8]
 [16 18]
 [21 23]]


### Change the values 1, 10, 19 and 22 in the array to -2

In [13]:
# Answer
value_change = a.copy()
value_change[[0,2,3,4],[1,0,4,2]] = -2
print("After changing values 1, 10, 19 and 22 in the array to -2 the array a becomes :: \n",value_change)


After changing values 1, 10, 19 and 22 in the array to -2 the array a becomes :: 
 [[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [19]:
# Answer here

b = a.copy()

mask = ( b == 1 ) | (b == 10) | (b == 19) | (b == 22)
b[mask] = -2



print("After Inserting values by boolean indexing the array becomes \n",b)

After Inserting values by boolean indexing the array becomes 
 [[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 18 -2]
 [20 21 -2 23 24]]


### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [15]:
# Answer here

s = a.copy()

# select rows with boolean indexing
row_indices = [0, 1, 3]

# sub-array using slicing and boolean indexing

sub_array = s[row_indices][:, [0, 3]]

print(sub_array)

[[ 0  3]
 [ 5  8]
 [15 18]]


### Calculating the sum, min and max of all diagonal values

In [16]:
# Answer here

diag_values = np.diagonal(a)
print("The diagnol elements are :: ", diag_values)
print("The sum of diagnol elements is :: ",diag_values.sum())
print("The minimum of diagnol elements is :: ",diag_values.min())
print("The maximum of diagnol elements is :: ",diag_values.max())

The diagnol elements are ::  [ 0  6 12 18 24]
The sum of diagnol elements is ::  60
The minimum of diagnol elements is ::  0
The maximum of diagnol elements is ::  24


### Calculate the sum of differences between the 2nd row and 2nd last column

In [17]:
# Answer here

sec_row = a[1,:]
sec_last_col = a[:,-2]

print("second row is ", sec_row)
print("second col is ", sec_last_col)

print("The sum of differences between the 2nd row and 2nd last column is :: ",(sec_row-sec_last_col).sum() )

second row is  [5 6 7 8 9]
second col is  [ 3  8 13 18 23]
The sum of differences between the 2nd row and 2nd last column is ::  -30


### Create a new array that is the sum of even rows and odd rows

In [18]:
# Answer here
rows_even = a[::2]
rows_odd = a[1::2]

print("even rows are :: \n",rows_even)
print("odd rows are :: \n",rows_odd)


even_sum = np.sum(rows_even, axis=0)
odd_sum = np.sum(rows_odd,axis = 0)


new_array = even_sum+odd_sum 
print("The new array is :: ",new_array)

even rows are :: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
odd rows are :: 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]
The new array is ::  [50 55 60 65 70]


## You are done. Good job!