In [2]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [2]:
# Answer Here
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


# Type
Accuire type of list in python.

In [7]:
# Answer Here
print(type(list1))

<class 'list'>


# Creatation of Arrays
1.SIMPLE ARRAY CREATION

2.CHECKING THE TYPE

3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS

4.Array dim

5.Array Shape

6.BYTES PER ELEMENT

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [29]:
# Int array
# Answer Here


# Question 1 : Create Array
arr = np.arange(6)
print("Question 1 -- The array is :: ",arr)
#  2 : type of array
print("Question 2 -- The type of array is :: ",type(arr))

#  3 : Numerical type of elements of array
print("Question 3 -- The int type of array is :: ",arr.dtype)

#  4: Checking No. of Dimensions
print("Question 4 -- No of dimensions in array is :: ",arr.ndim)

#  5: Checking shape of array
print("Question 5 -- The shape of array is :: ",arr.shape)


#  6: Bytes per element
print("Question 6 -- The bytes per element are :: ",arr.itemsize)

#  7: BYTES OF MEMORY USED, How many bytes for one array element
#     nbytes = arr.size ×  arr.itemsize

print("Question 7 -- The bytes for one array element is :: ",arr.nbytes)


#  8: Total bytes 

total_bytes = arr.size * arr.itemsize
print("Question 8 -- Total bytes in array:", total_bytes)

Question 1 -- The array is ::  [0 1 2 3 4 5]
Question 2 -- The type of array is ::  <class 'numpy.ndarray'>
Question 3 -- The int type of array is ::  int32
Question 4 -- No of dimensions in array is ::  1
Question 5 -- The shape of array is ::  (6,)
Question 6 -- The bytes per element are ::  4
Question 7 -- The bytes for one array element is ::  24
Question 8 -- Total bytes in array: 24


In [9]:
# Decimal array

arr = np.arange(6,dtype="float32")
print("The arrray is :: ",arr)
print("The dtype of array is :: ",arr.dtype)
#Answer Here

The arrray is ::  [0. 1. 2. 3. 4. 5.]
The dtype of array is ::  float32


9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [31]:
#Question No. 9
# Create a float value
float_value = 3.14
print("The float_value is ", float_value)
# Assign a float valu  to int32
int_value = np.int32(float_value)

print("Question 9 -- After assigning float value to int 32 it becomes :: ",int_value) 

#Question No. 10

arr = np.ones((2, 3), dtype=float)
# Fill the array with a specified value (e.g., 5.0)
arr.fill(5.0)
# Print the filled array
print("Question 10 -- After filling array using .fill() with 5.0 it becomes : ",arr)


The float_value is  3.14
Question 9 -- After assigning float value to int 32 it becomes ::  3
Question 10 -- After filling array using .fill() with 5.0 it becomes :  [[5. 5. 5.]
 [5. 5. 5.]]


11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function tocreate an array with step of from 1.0 to 3.0

In [28]:
# Answer Here

a1 = np.arange(5)
a2 = np.arange(5)
print(f"array 1 is {a1} and array 2 is {a2}")

#Question 11 -- ADD two arrays 

print("Question 11 -- The addition of array 1 and array 2 is ::", a1+a2)

#Question 12 -- Multiply both arrays 
print("Question 12 -- The addition of array 1 and array 2 is ::", a1*a2)

#Question 13 -- Use ** operator in array operation
print("Question 13 -- The square of array using ** operator is  ::",a1**2 )


#Question 14 -- Create array from 0.0 to 11.0
arr_cr = np.arange(0,12,dtype="float32")
print("Question 14 -- The square of array using ** operator is  ::",arr_cr )


#Question 15 -- Multiply entire value with a scalar valur c = (2.0*np.pi)
arr_multiply = np.arange(4) 
c = 2.0*np.pi
print("Question 15 -- The multiplication of array with scalar value 2.0*np.pi is   ::",arr_multiply*c )


#Question 16 -- use np.arange function to create an array with step of from 1.0 to 3.0
arr_step = np.arange(0,15,3)
print("Question 16 -- The array with step of from 1.0 to 3.0  ::",arr_step )

array 1 is [0 1 2 3 4] and array 2 is [0 1 2 3 4]
Question 11 -- The addition of array 1 and array 2 is :: [0 2 4 6 8]
Question 12 -- The addition of array 1 and array 2 is :: [ 0  1  4  9 16]
The square of array using ** operator is  :: [ 0  1  4  9 16]
The square of array using ** operator is  :: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
The multiplication of array with scalar value 2.0*np.pi is   :: [ 0.          6.28318531 12.56637061 18.84955592]
The array with step of from 1.0 to 3.0  :: [ 0  3  6  9 12]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8. Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [36]:
# Answer Here



#Question 1 -- Array indices from 1 to 3 
aa = np.arange(8)
print("The actual array is :: ",aa)
print("Question 1 -- The array indices from 1 to 3 are ",aa[1:4])

#Question 2 -- Negative indexing
print("Question 2 -- Last 3 elements of the array using negative indexing is  ::", aa[-3:])


#Question 3 -- Omitted boundries first 3 elements
print("Question 3 -- Omitted boundry from beginning of the array  ::", aa[:3])


#Question 4 -- Grab last 2 elements
print("Question 4 -- Last 2 elements are   ::", aa[-2:])

#Question 5 -- Grab every other element (except last 2)
print("Question 5 -- Every element except last 2 elements are   ::", aa[:-2])

#Question 6 -- Slicing the last two elements returns the data there
print("Question 6 -- Slicing last 2 elements are   ::", aa[-2:])

#Question 7 -- can we insert iterateable of 2 or scalar
arr_ite = np.array([[5,6],[7,8]])
print("The original array is :: \n",arr_ite)
arr_ite[0] = [0,0]
print("After inserting 2 elements at 0th position it becomes :: \n",arr_ite)

arr_ite[1,0] = 200
print("After inserting scalar  element 200 at 1st row and 0 column is :: \n",arr_ite)


#Question 8 -- Create a slice containing two elements of a . Changing b changed a!
orig_arr = np.arange(8)
print("Question 7 -- The original array is ", orig_arr)

arr_b = orig_arr[:2]
arr_b[0] = 555

print("The array b is ",arr_b)
print("By changing the 0th element of arr_b the original array is also changed   ::", orig_arr)


#Question 9 -- The array ab = [[0,1,2,3,4],[1,2,3,4,5]] . Extract values from row 3 to onward and from col 0,2,5

#******Note -- There's a mistake in question. Array contains 2 rows but the question is given that extract
#rows from 3 to onward

ab = np.array([[0,1,2,3,4],[1,2,3,4,5]])
print("Question 8 -- The array is :: \n",ab)
print("Extracted values are :: ",ab[1,[0,2,4]])


#Question 10 -- Perform some masking on a = np.arange(0,36).reshape(6,6) with mask = np.array([1, 0, 1, 0, 0, 1])

ar_mask = np.arange(36).reshape(6,6)
mask = np.array([1, 0, 1, 0, 0, 1],dtype=bool)

#The above mask will hide the row 1,3 and 4 and will just show row 0,2,5
ar_mask[mask]




The actual array is ::  [0 1 2 3 4 5 6 7]
Question 1 -- The array indices from 1 to 3 are  [1 2 3]
Question 2 -- Last 3 elements of the array using negative indexing is  :: [5 6 7]
Question 3 -- Omitted boundry from beginning of the array  :: [0 1 2]
Question 4 -- Last 2 elements are   :: [6 7]
Question 5 -- Every element except last 2 elements are   :: [0 1 2 3 4 5]
Question 6 -- Slicing last 2 elements are   :: [6 7]
The original array is :: 
 [[5 6]
 [7 8]]
After inserting 2 elements at 0th position it becomes :: 
 [[0 0]
 [7 8]]
After inserting scalar  element 200 at 1st row and 0 column is :: 
 [[  0   0]
 [200   8]]
Question 7 -- The original array is  [0 1 2 3 4 5 6 7]
The array b is  [555   1]
By changing the 0th element of arr_b the original array is also changed   :: [555   1   2   3   4   5   6   7]
Question 8 -- The array is :: 
 [[0 1 2 3 4]
 [1 2 3 4 5]]
Extracted values are ::  [1 3 5]


array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [30, 31, 32, 33, 34, 35]])

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [42]:
# Answer Here

#Question 1 -- create array with arange with [start,stop,step]
arr_fun = np.arange(1.0,101,10)
print("Question 1 -- The  array with start 1, end 101 and step 10 is :: ",arr_fun)


#Question 2 -- create array with ones and zeros
arr_zeros = np.zeros(5)
arr_ones = np.ones(4)
print(f"Question 2 -- The zeros array is {arr_zeros} and the ones array is {arr_ones} ")


#Question 3 -- Generate n by n identity matrix
arr_identity = np.identity(3)
print("Question 3 -- The identity matrix is :: \n", arr_identity)


#Question 4 --  use empty, full, and fill, max, min, std, mean, var, argmax, linspace

# empty() and fill
emp_arr = np.empty((3,3))

print("Question 4 functions are given below \n")
print("The empty array is :: ", emp_arr)

#fill()
emp_arr.fill(5.0) 
print("After fill 5.0 in empty array the array becomes :: ",emp_arr)

#full()
arr_full = np.full((3, 3), 10.0)
print("The array shaped (3,3) with full value 10.0 is :: ", arr_full)

arr_stats = np.arange(16).reshape(4,4)
print("The original array is :: \n",arr_stats)

print("The minimum of array is :: ", arr_stats.min())
print("The maximum of array is :: ", arr_stats.max())
print("The std of array is :: ", arr_stats.std())
print("The mean of array is :: ", arr_stats.mean())
print("The var of array is :: ", arr_stats.var())
print("The argmax (index of maximum number) of array is :: ", arr_stats.argmax())


# Array using linspace

arr_linspace = np.linspace(0,10,5)
print("Question 5 -- Array created using linspace is :: ",arr_linspace)


#Question 6
a = np.arange(-15, 15).reshape(5, 6) ** 2
#The maximum of each row 
print("The maximum of each row is :: ",a.max(axis=1))
#The mean of each column 
print("The mean of each column is :: ",a.mean(axis=0))
#The position of overall minimum 
print("The position of overall minimum in the given array is ::",a.argmin())

Question 1 -- The  array with start 1, end 101 and step 10 is ::  [ 1. 11. 21. 31. 41. 51. 61. 71. 81. 91.]
Question 3 -- The identity matrix is :: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Question 4 functions are given below 

The empty array is ::  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
After fill 5.0 in empty array the array becomes ::  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
The array shaped (3,3) with full value 10.0 is ::  [[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
The original array is :: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The minimum of array is ::  0
The maximum of array is ::  15
The std of array is ::  4.6097722286464435
The mean of array is ::  7.5
The var of array is ::  21.25
The argmax (index of maximum number) of array is ::  15
Question 5 -- Array created using linspace is ::  [ 0.   2.5  5.   7.5 10. ]
The maximum of each row is ::  [225  81   9  64 196]
The mean of each column is ::  [81. 76. 73. 72. 73. 76.]
The position of overall minimum in

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [46]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here

#Zip function
zip_fun = zip(a,b)
# Convert the zipped iterator into a NumPy array
result = np.array(list(zip_fun))
print("Zip function on array a and b results in :: ",result)

#create an array  which would be the sum of corresponding elements of two arrays using for loop

arr_sum = []
for i in range(len(a)):
    arr_sum.append(a[i]+b[i])
sum_result = np.array(arr_sum)
print("The sum of two arrays using for loop is :: ", sum_result)

Zip function on array a and b results in ::  [[1 2]
 [2 3]
 [3 4]
 [4 5]]
The sum of two arrays using for loop is ::  [3 5 7 9]


In [48]:
#For loop to add corresponding elements in two lists

l1 = [1,2,3,4]
l2 = [4,5,6,6]
new_list = []
for i in range(len(l1)):
    new_list.append(l1[i] + l2[i])
print(new_list)

# Answer Here

[5, 7, 9, 10]


# <b>Broadcasting<b>

In [28]:

#Example of Broadcasting
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(f"The shape of array 1 is {a.shape} and the shape of array b is {b.shape}")
print("The result of broadcasting is :: \n",a+b)



The shape of array 1 is (4, 3) and the shape of array b is (3,)
The result of broadcasting is :: 
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [1]:
#Example of Error in Broadcasting because of shape 

# Error will Generate because broadcasting rules are not applicable here

a1 = np.arange(12).reshape(4,3)
b2 = np.arange(6)
print(f"The shape of array 1 is {a1.shape} and the shape of array b is {b1.shape}")
print("The result of broadcasting is Error because shape are mismatched:: \n",a+b)

NameError: name 'np' is not defined

1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [19]:
# Answer Here
arr_reduce = np.arange(9).reshape(3,3)
print("The actaull array is :: \n" ,arr_reduce)
result = np.add.reduce(arr_reduce, 1) # Sum along axis 1 , bydefault is 0
print("The result of reduce is :: ",result)


arr_accamulate = np.array([[1, 2], [3, 4],[5,6]])
print("The actuall array for accamulate is :: \n",arr_accamulate)
result_accu = np.multiply.accumulate(arr_accamulate, 0)
print("The result of accumulate is :: \n",result_accu)

The actaull array is :: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
The result of reduce is ::  [ 3 12 21]
The actuall array for accamulate is :: 
 [[1 2]
 [3 4]
 [5 6]]
The result of accumulate is :: 
 [[ 1  2]
 [ 3  8]
 [15 48]]
